"""Bounded field-coupled liquid Plateau-border / global-CFD foundation."""
from __future__ import annotations
from dataclasses import dataclass, replace
import math
from typing import Any
from bubblelab.solvers.plateau_border import PlateauBorderModel, PlateauBorderSettings
from bubblelab.solvers.plateau_border.model import PlateauBorderEvolution, _perform_event_geometry_switch
from bubblelab.solvers.transient.network import t1_hydrodynamics as _direct_t1
from .t1 import T1GlobalCFDSettings, T1SharedFieldResult, _hydrodynamic_resistance_on_pair, _pair_targets, solve_t1_shared_field
MODEL_ID="LOCAL_3D_LIQUID_BORDER_SHARED_GLOBAL_CFD_T1"; SUPPORTED_CLASS="bounded-local-3d-liquid-border-shared-eulerian-t1"
@dataclass(frozen=True)
class LiquidBorderGlobalCFDSettings:
    base:T1GlobalCFDSettings=T1GlobalCFDSettings(); border:PlateauBorderSettings=PlateauBorderSettings(surface_tension_n_m=0.03,liquid_viscosity_pa_s=0.12,core_radius_m=0.010,time_step_s=2.0e-3,maximum_time_s=240.0); maximum_steps:int=64; minimum_border_feedback_fraction:float=0.02; maximum_traction_mismatch:float=0.20
    def validate(self): self.base.validate(); self.border.validate()
@dataclass(frozen=True)
class LiquidBorderGlobalCFDResult:
    model:str; supported_class:str; before:Any; after:Any; pre_field:T1SharedFieldResult; post_field:T1SharedFieldResult; event_time_s:float; frozen_border_event_time_s:float; event_time_shift_fraction:float; initial_liquid_volume_m3:float; final_liquid_volume_m3:float; maximum_liquid_relative_error:float; maximum_gas_volume_relative_error:float; maximum_traction_mismatch:float; initial_core_volume_m3:float; final_core_volume_m3:float; final_reservoir_volume_m3:float; liquid_segment_vertices_m:tuple; liquid_segment_cells:tuple; adjacency_before:tuple; adjacency_after:tuple; preserved_region_ids:tuple; authoritative_grid_preserved:bool; steps:int
    def as_dict(self): return {"model":self.model,"supported_class":self.supported_class,"event":{"field_coupled_event_time_s":self.event_time_s,"frozen_border_event_time_s":self.frozen_border_event_time_s,"event_time_shift_fraction":self.event_time_shift_fraction,"steps":self.steps},"liquid_border":{"representation":"triangular-prism local 3D segment with connected reservoir","vertices_m":[list(v) for v in self.liquid_segment_vertices_m],"cells":[list(c) for c in self.liquid_segment_cells],"initial_core_volume_m3":self.initial_core_volume_m3,"final_core_volume_m3":self.final_core_volume_m3,"final_reservoir_volume_m3":self.final_reservoir_volume_m3,"initial_total_volume_m3":self.initial_liquid_volume_m3,"final_total_volume_m3":self.final_liquid_volume_m3,"maximum_relative_volume_error":self.maximum_liquid_relative_error},"topology":{"adjacency_before":[list(v) for v in self.adjacency_before],"adjacency_after":[list(v) for v in self.adjacency_after],"preserved_region_ids":list(self.preserved_region_ids),"maximum_gas_volume_relative_error":self.maximum_gas_volume_relative_error},"field":{"authoritative_grid_preserved":self.authoritative_grid_preserved,"maximum_traction_mismatch":self.maximum_traction_mismatch,"pre":self.pre_field.as_dict(),"post":self.post_field.as_dict()}}
def _prism(r,l):
    h=math.sqrt(3)*r; a=((0.,-r,-h/3),(0.,r,-h/3),(0.,0.,2*h/3)); return a+tuple((l,y,z) for _,y,z in a),((0,1,2),(3,5,4),(0,3,4,1),(1,4,5,2),(2,5,3,0))
def run_liquid_border_global_cfd_transition(solver:Any,topology_state:Any,settings:LiquidBorderGlobalCFDSettings|None=None):
    cfg=settings or LiquidBorderGlobalCFDSettings(); cfg.validate(); e=_direct_t1.detect_direct_t1_eligibility(topology_state,cfg.base.direct)
    if not e.eligible or e.neighborhood is None: raise ValueError(f"unsupported liquid-border T1 neighborhood: {e.reason}")
    n=e.neighborhood; border=PlateauBorderModel(topology_state,cfg.border); ids=tuple(sorted(r.id for r in topology_state.to_network().regions)); grid_id=id(solver.grid); cap=_direct_t1._direct_gap_capillary_force(topology_state.to_network(),n); total=cfg.border.total_liquid_volume_m3; core=total*cfg.border.initial_core_volume_fraction; gap=e.initial_gap_m
    base_speed=cfg.base.event_mobility_m_per_n_s*cap; field=solve_t1_shared_field(solver,_pair_targets(solver,n.old_adjacent_regions,relative_speed_m_s=base_speed,drift_speed_m_s=cfg.base.pre_event_drift_speed_m_s,opening=False),phase="PRE_T1_LIQUID_BORDER",settings=cfg.base); resistance=_hydrodynamic_resistance_on_pair(solver,n.old_adjacent_regions,field); maxm=max(field.aggregate_constraint_traction_relative_mismatch,*(v for _,v in field.front_constraint_traction_relative_mismatch)); state=replace(border.initial_state(),gap_m=gap,core_liquid_volume_m3=core,reservoir_liquid_volume_m3=total-core); forces=border.forces(state); bias=max(-.9,min(.9,resistance/max(cap,1e-30))); flow=forces.redistribution_flow_m3_s*(1+bias); frozen=(gap-border.event_gap_m)/base_speed; coupled_drive=max(cfg.base.minimum_net_driving_force_n,forces.net_driving_force_n-resistance); speed=cfg.base.event_mobility_m_per_n_s*coupled_drive; elapsed=(gap-border.event_gap_m)/speed; core=min(max(core-flow*elapsed,total*1e-12),total*(1-1e-12))
    evolution=PlateauBorderEvolution(samples=(),event_time_s=elapsed,initial_gap_m=e.initial_gap_m,event_gap_m=border.event_gap_m,initial_liquid_volume_m3=total,final_liquid_volume_m3=total,maximum_liquid_relative_error=0.); switched=_perform_event_geometry_switch(topology_state,border,evolution); after=switched.after; post=solve_t1_shared_field(solver,_pair_targets(solver,n.opposite_regions,relative_speed_m_s=cfg.base.post_event_opening_speed_m_s,drift_speed_m_s=cfg.base.pre_event_drift_speed_m_s,opening=True),phase="POST_T1_LIQUID_BORDER",settings=cfg.base); maxm=max(maxm,post.aggregate_constraint_traction_relative_mismatch,*(v for _,v in post.front_constraint_traction_relative_mismatch)); final=replace(border.initial_state(),gap_m=border.event_gap_m,core_liquid_volume_m3=core,reservoir_liquid_volume_m3=total-core); r=border.forces(final).core_radius_m; verts,cells=_prism(r,border.line_length_m); gaserr=max((v for _,v in switched.volume_errors_after),default=0.); return LiquidBorderGlobalCFDResult(MODEL_ID,SUPPORTED_CLASS,topology_state,after,field,post,elapsed,frozen,abs(elapsed-frozen)/max(frozen,1e-30),total,total,0.,gaserr,maxm,total*cfg.border.initial_core_volume_fraction,core,total-core,verts,cells,switched.adjacency_before,switched.adjacency_after,ids,id(solver.grid)==grid_id,1)
