"""Durable evidence catalog for the Bubble Lab R1-R39 completion audit."""
from __future__ import annotations


def row(
    status: str,
    evidence: list[str],
    gap: str,
    closure: str,
    *,
    benchmarks: list[str] | None = None,
    features: dict[str, str] | None = None,
) -> dict[str, object]:
    return {
        "status": status,
        "evidence": evidence,
        "benchmarks": benchmarks or [],
        "features": features or {},
        "gap": gap,
        "closure": closure,
    }


CATALOG: dict[str, dict[str, object]] = {
    "R1": row(
        "PARTIAL",
        ["bubblelab/docs/physics/PHYSICS_MODEL.md", "bubblelab/solvers/equilibrium/solver.py", "bubblelab/solvers/transient/solver.py", "bubblelab/runtime/runner.py", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-transient-release-acceleration.json"],
        "The repository contains physical equilibrium and transient solvers with exact B03/B07/B08/B12 reference-model release qualification, but material topology-integration, live-transport, physical-device and deferred-physics gaps remain.",
        "Close or explicitly defer the remaining R38 integration gaps without replacing solver physics with browser-only behavior.",
        features={"physical_solver_stack": "MODELED", "exact_transient_release_qualification": "RESOLVED", "visual_substitute_as_physics": "NOT_IMPLEMENTED"},
    ),
    "R2": row(
        "SATISFIED",
        ["bubblelab/runtime/runner.py", "bubblelab/contracts/frame.schema.json", "bubblelab/viewer/src/renderer.ts", "bubblelab/viewer/src/optics.ts"],
        "No completion gap identified for solver/render-state separation in the current architecture.",
        "Retain canonical solver outputs as authoritative when extending rendering.",
        features={"solver_render_separation": "RESOLVED"},
    ),
    "R3": row(
        "SATISFIED",
        ["bubblelab/viewer/src/camera.ts", "bubblelab/viewer/src/main.ts", "bubblelab/viewer/src/mobile.ts", "bubblelab/viewer/test/mobile.test.mjs", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-mobile-webkit-verification.json"],
        "Desktop navigation, deterministic touch/navigation policy and real Playwright WebKit mobile-engine behavior are implemented; physical-device qualification remains isolated to R28.",
        "Keep navigation and WebKit-engine regression tests when camera or gesture behavior changes.",
        features={"desktop_navigation": "RESOLVED", "touch_navigation_policy": "RESOLVED", "webkit_mobile_engine": "RESOLVED"},
    ),
    "R4": row(
        "PARTIAL",
        ["bubblelab/contracts/scenario.schema.json", "bubblelab/viewer/src/lab.ts", "bubblelab/viewer/test/lab-ui.test.mjs", "bubblelab/runtime/runner.py"],
        "Scenario editing covers bubble position, size and velocity intent, but the authoritative runner slices still impose restricted bubble-count/topology combinations and transient execution does not provide arbitrary live initial-state creation.",
        "Provide an authoritative runtime path for arbitrary add/create states, including supported initial velocity, and validate it end to end.",
        features={"scenario_bubble_creation": "RESOLVED", "arbitrary_live_runtime_creation": "NOT_IMPLEMENTED"},
    ),
    "R5": row(
        "SATISFIED",
        ["bubblelab/viewer/src/main.ts", "bubblelab/viewer/src/labPanel.ts", "bubblelab/viewer/test/viewer.test.mjs", "bubblelab/viewer/test/lab-ui.test.mjs"],
        "Selection, highlighting and deletion controls are present in the editor/viewer slice.",
        "Retain selection/deletion regression coverage when editing behavior changes.",
        features={"selection_and_delete": "RESOLVED"},
    ),
    "R6": row(
        "SATISFIED",
        ["bubblelab/solvers/equilibrium/solver.py", "bubblelab/validation/equilibrium_suite.py", "bubblelab/solvers/transient/release_benchmarks.py", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-transient-release-acceleration.json"],
        "Young-Laplace behavior is validated in equilibrium and the repository-defined transient reference model now has exact B12 fine-bulk release qualification using a B02-qualified tracked surface.",
        "Retain the exact B12 gate and do not reinterpret this reference-model qualification as resolved singular multiphase CFD.",
        benchmarks=["B02", "B12", "B13"],
        features={"equilibrium_young_laplace": "RESOLVED", "transient_capillary_pressure": "RESOLVED"},
    ),
    "R7": row(
        "SATISFIED",
        ["bubblelab/solvers/equilibrium/energy.py", "bubblelab/solvers/transient/release_benchmarks.py", "bubblelab/solvers/transient/remeshing.py", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-transient-release-acceleration.json"],
        "Equilibrium volume/energy, conservative remeshing and exact long-window transient B03/B07 release gates are accepted for the repository-defined reference model.",
        "Retain B03/B07 exact qualification and conservative-remeshing regression coverage.",
        benchmarks=["B01", "B03", "B07", "B13", "B14"],
        features={"equilibrium_volume_energy": "RESOLVED", "transient_long_window_conservation": "RESOLVED"},
    ),
    "R8": row(
        "PARTIAL",
        ["bubblelab/solvers/equilibrium/shared_geometry.py", "bubblelab/solvers/equilibrium/shared_benchmarks.py", "bubblelab/solvers/equilibrium/tests/test_shared_film.py", "bubblelab/runtime/runner.py"],
        "Shared-film equilibrium is resolved in its dedicated solver, but the accepted canonical transient runtime still lacks shared-film topology/network continuation.",
        "Integrate supported shared-film/contact topology into the authoritative transient multi-bubble runtime and validate the combination.",
        benchmarks=["B04", "B05"],
        features={"shared_film_equilibrium": "RESOLVED", "shared_film_transient_runtime": "NOT_IMPLEMENTED"},
    ),
    "R9": row(
        "PARTIAL",
        ["bubblelab/solvers/equilibrium/plateau.py", "bubblelab/solvers/equilibrium/plateau_benchmarks.py", "bubblelab/solvers/equilibrium/tests/test_plateau.py", "bubblelab/runtime/runner.py"],
        "Plateau-junction force balance and angle diagnostics are implemented for equilibrium, while dynamic multi-junction transient transport is not accepted in the canonical runtime.",
        "Add and validate an authoritative multi-junction runtime path for dynamic Plateau-network behavior.",
        benchmarks=["B06"],
        features={"plateau_equilibrium": "RESOLVED", "dynamic_multi_junction_runtime": "NOT_IMPLEMENTED"},
    ),
    "R10": row(
        "PARTIAL",
        ["bubblelab/solvers/transient/solver.py", "bubblelab/solvers/transient/geometry.py", "bubblelab/validation/transient_suite.py", "bubblelab/runtime/runner.py"],
        "Transient deformation responds to configured forcing, but accepted runtime integration does not yet demonstrate the full multi-bubble shared-contact neighborhood combination.",
        "Qualify multi-bubble/contact deformation through an authoritative transient network runtime path and final integrated validation.",
        features={"transient_free_deformation": "MODELED", "multi_bubble_dynamic_contact": "NOT_IMPLEMENTED"},
    ),
    "R11": row(
        "PARTIAL",
        ["bubblelab/solvers/transient/grid.py", "bubblelab/solvers/transient/solver.py", "bubblelab/solvers/transient/release_benchmarks.py", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-transient-release-acceleration.json"],
        "Gravity, ambient density/viscosity and wind are modeled and B12 is exactly release-qualified for the repository-defined reference model, but resolved bulk no-slip wall CFD and requested CFD/VOF/level-set combinations remain explicitly unavailable.",
        "Implement and qualify resolved ambient-fluid/wall-CFD claims before promoting them beyond MODELED; keep the accepted B12 reference-model evidence intact.",
        benchmarks=["B09", "B12"],
        features={"ambient_flow_reference_model": "MODELED", "transient_b12_release": "RESOLVED", "resolved_bulk_wall_cfd": "NOT_IMPLEMENTED"},
    ),
    "R12": row(
        "SATISFIED",
        ["bubblelab/contracts/frame.schema.json", "bubblelab/python/bubblelab_contract/models.py", "bubblelab/solvers/thinfilm/gas.py", "bubblelab/viewer/src/lab.ts"],
        "The contract and gas-transfer model represent pressure, temperature, amount/species and related bubble state at the architectural level required by R12.",
        "Preserve these fields across future solver adapters.",
        features={"internal_gas_state": "RESOLVED"},
    ),
    "R13": row(
        "PARTIAL",
        ["bubblelab/solvers/thinfilm/gas.py", "bubblelab/runtime/thinfilm_runtime.py", "bubblelab/runtime/tests/test_thinfilm_runtime.py", "bubblelab/runtime/runner.py"],
        "Pressure-driven pair gas transfer/coarsening is modeled in the thin-film backend, but it is not supported in the transient coupled network runtime and remains limited to the supported pair/shared-film slice.",
        "Integrate gas transfer with the authoritative transient multi-bubble path or keep the limitation explicit in final acceptance.",
        benchmarks=["B15"],
        features={"pairwise_gas_diffusion": "MODELED", "transient_gas_diffusion": "NOT_IMPLEMENTED"},
    ),
    "R14": row(
        "PARTIAL",
        ["bubblelab/solvers/thinfilm/surface.py", "bubblelab/runtime/thinfilm_runtime.py", "bubblelab/solvers/transient/thinfilm_adapter.py", "bubblelab/solvers/transient/remeshing.py"],
        "Drainage, surfactant transport and variable tension are modeled for supported tracked-film coupling, but integrated shared/contact-film network transport is not available in the accepted canonical transient runtime.",
        "Validate the intended contact/shared-film transport combination, including conservative remeshing, before claiming full R14 coverage.",
        benchmarks=["B14"],
        features={"tracked_film_transport": "MODELED", "shared_contact_film_transport": "NOT_IMPLEMENTED"},
    ),
    "R15": row(
        "PARTIAL",
        ["bubblelab/solvers/events/engine.py", "bubblelab/runtime/event_runtime.py", "bubblelab/runtime/postcoalescence_runtime.py", "bubblelab/validation/transient_suite.py", "bubblelab/runtime/runner.py"],
        "Conservative coalescence event bookkeeping and short post-event relaxation are modeled, but singular coalescence CFD and fully integrated dynamic-network coalescence are not claimed.",
        "Integrate the event path with the authoritative dynamic-network runtime while preserving the explicit singular-CFD limitation.",
        benchmarks=["B10", "B16"],
        features={"coalescence_event_bookkeeping": "MODELED", "post_coalescence_relaxation": "MODELED", "singular_coalescence_cfd": "NOT_IMPLEMENTED"},
    ),
    "R16": row(
        "PARTIAL",
        ["bubblelab/solvers/events/engine.py", "bubblelab/scenarios/runtime/user-burst.scenario.json", "bubblelab/runtime/event_runtime.py", "bubblelab/research/fragmentation/README.md"],
        "Rupture and user-triggered burst are modeled in the event slice, but production splitting/fragmentation remains research-only and rim/droplet physics is not implemented.",
        "Implement and validate production splitting/fragmentation before claiming that portion of R16; otherwise retain it as an explicit deferred capability.",
        benchmarks=["B16"],
        features={"rupture_event": "MODELED", "user_burst": "MODELED", "production_fragmentation": "NOT_IMPLEMENTED", "rim_droplet_physics": "NOT_IMPLEMENTED"},
    ),
    "R17": row(
        "PARTIAL",
        ["bubblelab/solvers/boundary/contact.py", "bubblelab/runtime/boundary_runtime.py", "bubblelab/scenarios/runtime/transient-floor-contact.scenario.json", "bubblelab/viewer/src/lab.ts", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-boundary-ui-integration.json"],
        "Tracked-front wall contact, modeled wettability, canonical transient boundary runtime integration and solid-boundary UI editing are accepted; resolved bulk no-slip solid-fluid wall CFD remains explicitly unavailable.",
        "Retain the accepted boundary UI/runtime path and implement resolved no-slip wall-fluid coupling only if that higher-fidelity capability is required.",
        features={"tracked_front_boundary_contact": "MODELED", "solid_boundary_ui_integration": "RESOLVED", "resolved_no_slip_wall_cfd": "NOT_IMPLEMENTED"},
    ),
    "R18": row(
        "SATISFIED",
        ["bubblelab/viewer/src/lab.ts", "bubblelab/solvers/transient/release_benchmarks.py", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-transient-release-acceleration.json"],
        "Arbitrary gravity vectors are modeled/editable and exact B08 zero-gravity release qualification now includes the required full-time rotated repeat.",
        "Retain exact B08 qualification and gravity-vector/preset regression coverage.",
        benchmarks=["B08"],
        features={"gravity_vector": "RESOLVED", "zero_g_release_qualification": "RESOLVED"},
    ),
    "R19": row(
        "PARTIAL",
        ["bubblelab/viewer/src/replay.ts", "bubblelab/runtime/session_control.py", "bubblelab/viewer/src/sessionControl.ts", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-runtime-session-control.json", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-session-ui-integration.json"],
        "Authoritative PAUSE/RESUME/STEP/RUN_TO_TIME/RESET runtime-session semantics and deterministic UI command staging are accepted, while the browser still exports commands and imports authoritative bundles rather than using a direct live browser-to-solver transport.",
        "Add a direct live transport only if required; until then preserve the explicit external-CLI command/bundle handoff and keep replay navigation distinct from solver-session control.",
        features={"replay_time_control": "RESOLVED", "authoritative_runtime_session_control": "RESOLVED", "session_ui_command_staging": "RESOLVED", "browser_live_solver_transport": "NOT_IMPLEMENTED"},
    ),
    "R20": row(
        "PARTIAL",
        ["bubblelab/viewer/src/lab.ts", "bubblelab/solvers/transient/amr.py", "bubblelab/solvers/transient/solver.py", "bubblelab/runtime/runner.py", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-transient-release-acceleration.json"],
        "Fidelity selection and solver accuracy mechanisms exist and exact release gates are accepted, but not every high-end solver control/runtime combination is exposed through the canonical integrated path.",
        "Reconcile user-facing capability declarations with runnable backend combinations while preserving exact release-gate evidence.",
        features={"solver_accuracy_mechanisms": "MODELED", "exact_release_gates": "RESOLVED", "all_high_end_runtime_combinations": "NOT_IMPLEMENTED"},
    ),
    "R21": row(
        "SATISFIED",
        ["bubblelab/viewer/src/debug.ts", "bubblelab/viewer/src/renderer.ts", "bubblelab/solvers/transient/amr.py", "bubblelab/viewer/test/debug.test.mjs"],
        "Mesh/debug channels are available for the data produced by the current backends.",
        "Keep debug visualization aligned with canonical frame fields as solvers evolve.",
        features={"mesh_debug_visualization": "RESOLVED"},
    ),
    "R22": row(
        "SATISFIED",
        ["bubblelab/contracts/frame.schema.json", "bubblelab/viewer/src/debug.ts", "bubblelab/viewer/test/debug.test.mjs", "bubblelab/validation/transient_suite.py"],
        "Physics diagnostic channels and explicit capability classification are implemented for available backend data.",
        "Continue labeling unavailable channels rather than synthesizing them visually.",
        features={"physics_diagnostics": "RESOLVED"},
    ),
    "R23": row(
        "SATISFIED",
        ["bubblelab/contracts/frame.schema.json", "bubblelab/viewer/src/labPanel.ts", "bubblelab/viewer/src/debug.ts", "bubblelab/viewer/test/lab-ui.test.mjs"],
        "The canonical frame and inspector cover required per-bubble state for current outputs.",
        "Preserve required fields across future backends and topology events.",
        features={"per_bubble_inspector": "RESOLVED"},
    ),
    "R24": row(
        "SATISFIED",
        ["bubblelab/contracts/frame.schema.json", "bubblelab/viewer/src/labPanel.ts", "bubblelab/viewer/src/debug.ts", "bubblelab/viewer/test/debug.test.mjs"],
        "System-level diagnostics are represented and displayed for canonical replay frames.",
        "Keep compute/solver metrics explicit when a backend cannot provide a value.",
        features={"system_diagnostics_panel": "RESOLVED"},
    ),
    "R25": row(
        "SATISFIED",
        ["bubblelab/viewer/src/optics.ts", "bubblelab/viewer/src/renderer.ts", "bubblelab/viewer/test/optics.test.mjs", "bubblelab/viewer/src/lab.ts"],
        "Transparent-film rendering, Fresnel/optical behavior and thin-film color are implemented as renderer-only effects.",
        "Maintain the solver/render separation when adding higher-quality environment lighting.",
        features={"thin_film_optics": "RESOLVED"},
    ),
    "R26": row(
        "SATISFIED",
        ["bubblelab/solvers/equilibrium/shared_export.py", "bubblelab/viewer/src/renderer.ts", "bubblelab/viewer/src/debug.ts", "bubblelab/viewer/test/debug.test.mjs"],
        "Shared-film result data can be distinguished and visualized independently from outer-film presentation.",
        "Retain explicit shared/outer labeling for future multi-bubble runtime results.",
        features={"common_film_display": "RESOLVED"},
    ),
    "R27": row(
        "PARTIAL",
        ["bubblelab/viewer/src/lab.ts", "bubblelab/viewer/src/main.ts", "bubblelab/viewer/test/lab-ui.test.mjs", "bubblelab/runtime/event_runtime.py", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-session-ui-integration.json"],
        "The editor supports scenario manipulation, user-burst intent and authoritative session-command staging, but several actions remain scenario/export operations rather than direct live manipulation of a running solver over a browser transport.",
        "Validate or implement the required action set against an authoritative integrated runtime and retain edit-vs-run mode boundaries.",
        features={"scenario_direct_manipulation": "RESOLVED", "authoritative_session_command_staging": "RESOLVED", "live_browser_physics_manipulation": "NOT_IMPLEMENTED"},
    ),
    "R28": row(
        "UNVERIFIED",
        ["bubblelab/viewer/src/mobile.ts", "bubblelab/viewer/test/mobile.test.mjs", "bubblelab/viewer/MOBILE_WEBKIT_VERIFICATION.md", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-mobile-webkit-verification.json"],
        "Real Playwright WebKit mobile-engine verification passes at iPhone-class profiles, including the compact-layout fix, but physical iPhone Safari/device GPU behavior and native hardware multi-touch remain unverified.",
        "Run the documented verification on a physical iPhone Safari or credible device-browser service and archive device/browser/render/input evidence before claiming hardware certification.",
        features={"mobile_layout_gestures": "RESOLVED", "webkit_mobile_engine": "RESOLVED", "physical_iphone_safari": "NOT_IMPLEMENTED", "native_hardware_multitouch": "NOT_IMPLEMENTED"},
    ),
    "R29": row(
        "SATISFIED",
        ["bubblelab/runtime/runner.py", "bubblelab/runtime/bundle.py", "bubblelab/viewer/src/replay.ts", "bubblelab/viewer/src/runtimeBundle.ts"],
        "Backend result generation and Web replay are cleanly separated through canonical bundles.",
        "Keep replay consumers backend-neutral as new solver families are added.",
        features={"backend_viewer_separation": "RESOLVED"},
    ),
    "R30": row(
        "PARTIAL",
        ["bubblelab/contracts/checkpoint.schema.json", "bubblelab/runtime/checkpoint_runtime.py", "bubblelab/scenarios/runtime/checkpoint-transient.scenario.json", "bubblelab/scenarios/runtime/checkpoint-thinfilm.scenario.json", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-checkpoint-restart.json"],
        "Canonical scenario persistence plus exact same-build fresh-process transient/thin-film checkpoint/restart are accepted, but the requested reusable scenario family remains incomplete for many-bubble/network cases constrained by current runtime integration.",
        "Retain same-build checkpoint/restart evidence and add the missing reusable many-bubble/network scenarios after the authoritative network runtime exists; do not claim cross-version checkpoint portability.",
        features={"scenario_persistence": "RESOLVED", "same_build_checkpoint_restart": "RESOLVED", "cross_version_checkpoint_portability": "NOT_IMPLEMENTED", "complete_initial_scenario_set": "NOT_IMPLEMENTED"},
    ),
    "R31": row(
        "SATISFIED",
        ["bubblelab/runtime/runner.py", "bubblelab/runtime/checkpoint_runtime.py", "bubblelab/contracts/simulation-manifest.schema.json", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-checkpoint-restart.json"],
        "Seeds and deterministic same-build replay are stored and validated, and fresh-process same-build checkpoint continuation is qualified exactly for supported transient/thin-film state.",
        "Do not reinterpret same-build determinism as cross-platform bitwise identity or cross-version checkpoint portability without separate evidence.",
        benchmarks=["B11", "B15", "B16"],
        features={"same_build_reproducibility": "RESOLVED", "fresh_process_checkpoint_exact_continuation": "RESOLVED"},
    ),
    "R32": row(
        "SATISFIED",
        ["bubblelab/validation/equilibrium_suite.py", "bubblelab/validation/spec/BENCHMARK_MATRIX.md", "bubblelab/solvers/transient/release_benchmarks.py", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-transient-release-acceleration.json"],
        "The automated validation stack covers the benchmark matrix, and exact B03/B07/B08/B12 transient release qualification is accepted without weakened gates.",
        "Keep exact release qualification in the final validation wave and preserve its documented reference-model scope.",
        benchmarks=["B01", "B02", "B03", "B04", "B05", "B06", "B07", "B08", "B09", "B10", "B11", "B12", "B13", "B14", "B15", "B16"],
        features={"equilibrium_validation": "RESOLVED", "transient_release_validation": "RESOLVED"},
    ),
    "R33": row(
        "SATISFIED",
        ["bubblelab/viewer/src/lab.ts", "bubblelab/validation/transient_suite.py", "bubblelab/viewer/MOBILE_WEBKIT_VERIFICATION.md", "bubblelab/docs/physics/PHYSICS_MODEL.md"],
        "The UI/validation/docs distinguish RESOLVED, MODELED, VISUAL_ONLY and NOT_IMPLEMENTED behavior and explicitly preserve important limitations.",
        "Keep capability disclosures synchronized with runnable backend support.",
        features={"physical_transparency": "RESOLVED"},
    ),
    "R34": row(
        "SATISFIED",
        ["bubblelab/docs/physics/SOLVER_DECISION.md", "bubblelab/solvers/equilibrium/solver.py", "bubblelab/solvers/transient/solver.py", "bubblelab/solvers/thinfilm/surface.py"],
        "Multiple solver families coexist behind shared state/result boundaries.",
        "Preserve solver-neutral contracts when adding future methods.",
        features={"solver_flexibility": "RESOLVED"},
    ),
    "R35": row(
        "PARTIAL",
        ["bubblelab/viewer/src/lab.ts", "bubblelab/runtime/runner.py", "bubblelab/solvers/transient/solver.py", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-transient-release-acceleration.json"],
        "Multiple backends/fidelity declarations and exact transient release qualification exist, but maximum-realism integration remains constrained by unsupported dynamic network and other high-fidelity runtime combinations.",
        "Close the remaining high-fidelity runtime-integration gaps while retaining lower-fidelity modes and exact release evidence with explicit scope.",
        features={"multi_backend_fidelity": "MODELED", "exact_transient_release_qualification": "RESOLVED", "maximum_realism_integrated": "NOT_IMPLEMENTED"},
    ),
    "R36": row(
        "SATISFIED",
        ["bubblelab/contracts/frame.schema.json", "bubblelab/runtime/runner.py", "bubblelab/viewer/src/adapter.ts", "bubblelab/viewer/src/runtimeBundle.ts"],
        "State/contracts, solver runtime, file/replay layer and viewer are modularized around common formats.",
        "Keep adapter boundaries stable when adding new solver implementations.",
        features={"modular_architecture": "RESOLVED"},
    ),
    "R37": row(
        "SATISFIED",
        ["bubblelab/docs/PRODUCT_REQUIREMENTS.md", "bubblelab/validation/completion/evidence/HISTORICAL_EVIDENCE.md"],
        "The repository uses scoped Workers with explicit dependency and edit ownership; this is a process requirement for decomposition rather than physical feature evidence.",
        "Continue using non-overlapping task scopes for remaining work.",
        features={"worker_decomposition": "RESOLVED"},
    ),
    "R38": row(
        "PARTIAL",
        ["bubblelab/runtime/runner.py", "bubblelab/viewer/src/sessionControl.ts", "bubblelab/viewer/MOBILE_WEBKIT_VERIFICATION.md", "bubblelab/research/fragmentation/README.md", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-transient-release-acceleration.json", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-mobile-webkit-verification.json", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-runtime-session-control.json", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-session-ui-integration.json", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-checkpoint-restart.json", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-boundary-ui-integration.json"],
        "Exact B03/B07/B08/B12 release qualification, solid-boundary UI/runtime integration, authoritative runtime-session semantics, session UI staging and same-build checkpoint/restart are accepted. Integrated completion is still blocked by the unaccepted canonical transient shared-film/Plateau network path, absent live browser-to-solver transport, unverified physical iPhone Safari/native multi-touch, research-only production fragmentation, and explicitly unresolved bulk no-slip wall CFD.",
        "Close or explicitly defer each remaining integration/device/physics gap, then run final end-to-end validation against that resulting baseline.",
        benchmarks=["B03", "B07", "B08", "B12"],
        features={"exact_transient_release_qualification": "RESOLVED", "solid_boundary_integration": "RESOLVED", "authoritative_session_control": "RESOLVED", "same_build_checkpoint_restart": "RESOLVED", "multi_bubble_canonical_runtime": "NOT_IMPLEMENTED", "browser_live_solver_transport": "NOT_IMPLEMENTED", "physical_iphone_safari": "NOT_IMPLEMENTED", "production_fragmentation": "NOT_IMPLEMENTED", "resolved_no_slip_wall_cfd": "NOT_IMPLEMENTED"},
    ),
    "R39": row(
        "PARTIAL",
        ["bubblelab/docs/physics/PHYSICS_MODEL.md", "bubblelab/runtime/runner.py", "bubblelab/solvers/transient/release_benchmarks.py", "bubblelab/viewer/src/sessionControl.ts", "bubblelab/validation/completion/evidence/historical-deliveries/bubble-checkpoint-restart.json"],
        "Bubble Lab contains real physical models, exact transient release gates, authoritative session control and persistent same-build continuation, but the full laboratory statement cannot be claimed while R38 retains material network, live-transport, device and deferred-physics gaps.",
        "Complete final integrated validation without hiding unsupported physics or device claims behind visual behavior.",
        features={"physical_laboratory_direction": "MODELED", "complete_physical_laboratory": "NOT_IMPLEMENTED"},
    ),
}
