"""Post-Wave-19 evidence overlay for the Bubble Lab completion catalog."""
from __future__ import annotations

from copy import deepcopy

from .catalog import row
from .wave17_catalog import CATALOG as WAVE17_CATALOG


CATALOG = deepcopy(WAVE17_CATALOG)
CATALOG.update(
    {
        "R1": row(
            "PARTIAL",
            [
                "bubblelab/docs/physics/PHYSICS_MODEL.md",
                "bubblelab/runtime/session_control.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-live-runtime-editing.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-noslip-wall-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-precontact-multiregion-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-global-multiregion-cfd-coupling.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-general-3d-t1-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-singular-breakup-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-manybubble-gas-diffusion-network.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-multigap-manybubble-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-direct-3d-t1-hydrodynamics.json",
            ],
            "Wave 19 adds a conservative fixed-topology many-bubble pressure-driven gas network, a bounded three-bubble/two-simultaneous-gap global CFD path sharing one authoritative Eulerian field, and a bounded direct-geometry genuinely-3D T1 hydrodynamics path with real topology surgery and continuation. The ultimate maximum-realism laboratory is still incomplete because unrestricted topology-changing gas transport, T1-through-global-CFD/overlapping immersed supports, unrestricted continuous/singular 3D T1 liquid-border hydrodynamics, retracting-rim/ligament/droplet-spray and unrestricted multi-neck breakup, deforming-wall CFD, arbitrary coupled live surgery, and physical-device qualification remain outside accepted evidence.",
            "Preserve every accepted supported class and close each remaining unrestricted/device class only with independent measured evidence; do not widen bounded Wave-19 results by prose.",
            features={
                "physical_solver_stack": "MODELED",
                "exact_transient_release_qualification": "RESOLVED",
                "integrated_topology_slices": "RESOLVED",
                "live_authoritative_transport": "RESOLVED",
                "authoritative_base_transient_live_editing": "RESOLVED",
                "resolved_fixed_sdf_no_slip_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "supported_global_two_bubble_single_gap_multiregion_cfd": "MODELED",
                "bounded_genuine_non_coplanar_3d_t1": "RESOLVED",
                "supported_axisymmetric_slender_neck_pinchoff": "MODELED",
                "supported_manybubble_pressure_driven_gas_network": "MODELED",
                "bounded_three_bubble_two_gap_global_cfd": "MODELED",
                "bounded_direct_geometry_3d_t1_hydrodynamics": "MODELED",
                "maximum_realism_full_coupling": "NOT_IMPLEMENTED",
            },
        ),
        "R9": row(
            "SATISFIED",
            [
                "bubblelab/solvers/equilibrium/plateau.py",
                "bubblelab/runtime/transient_network_runtime.py",
                "bubblelab/scenarios/runtime/transient-network-plateau.scenario.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-transient-network-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-t1-production-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-general-3d-t1-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-direct-3d-t1-hydrodynamics.json",
            ],
            "No baseline R9 gap remains. The accepted equilibrium/transient network provides Plateau force/angle diagnostics and explicit junction geometry; Wave 17 qualified a bounded genuinely non-coplanar topology switch; and Wave 19 independently adds a direct current-mesh 3D capillary-traction event path with deterministic adjacency/incidence surgery, conservation, rotation invariance, conforming-subdivision invariance and authoritative continuation.",
            "Retain approximately-120-degree diagnostics and explicit topology/incidence records. Unrestricted arbitrary-admissible 3D T1, continuum curved-surface convergence, and resolved evolving/singular Plateau-border liquid CFD remain higher-fidelity extensions, not baseline R9 blockers.",
            benchmarks=["B06"],
            features={
                "plateau_equilibrium": "RESOLVED",
                "dynamic_multi_junction_runtime": "RESOLVED",
                "supported_t1_transaction": "RESOLVED",
                "bounded_genuine_non_coplanar_3d_t1": "RESOLVED",
                "bounded_direct_geometry_3d_t1_hydrodynamics": "MODELED",
            },
        ),
        "R10": row(
            "PARTIAL",
            [
                "bubblelab/solvers/transient/solver.py",
                "bubblelab/runtime/transient_network_runtime.py",
                "bubblelab/runtime/contact_runtime.py",
                "bubblelab/runtime/boundary_runtime.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-noslip-wall-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-precontact-multiregion-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-global-multiregion-cfd-coupling.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-multigap-manybubble-cfd-foundation.json",
            ],
            "Accepted runtime slices cover free deformation, gravity/wind forcing, contact deformation, resolved fixed-SDF no-slip walls, local thin-gap traction, Wave-17 global two-bubble/single-gap field feedback, and Wave-19 simultaneous three-front/two-gap field-derived response from one global solve. A single unrestricted maximum-realism runtime still does not combine every requested forcing with arbitrary simultaneous contact graphs, overlapping-support CFD, T1-through-CFD and deforming walls.",
            "Qualify only the remaining general forcing/contact/wall/CFD combinations required by the maximum-realism claim while retaining the fixed-SDF and separated-support boundaries.",
            features={
                "transient_free_deformation": "MODELED",
                "network_forcing": "MODELED",
                "contact_deformation": "MODELED",
                "resolved_fixed_sdf_no_slip_wall_cfd": "RESOLVED",
                "local_precontact_thin_gap_traction": "MODELED",
                "supported_global_two_bubble_single_gap_multiregion_cfd": "MODELED",
                "bounded_three_bubble_two_gap_global_cfd": "MODELED",
                "unified_maximum_realism_forcing": "NOT_IMPLEMENTED",
            },
        ),
        "R11": row(
            "PARTIAL",
            [
                "bubblelab/solvers/transient/grid.py",
                "bubblelab/solvers/transient/solver.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-noslip-wall-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-precontact-multiregion-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-global-multiregion-cfd-coupling.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-multigap-manybubble-cfd-foundation.json",
            ],
            "Gravity, ambient density/viscosity and wind retain exact release qualification; fixed-SDF no-slip wall flow and local thin-gap CFD remain accepted. Wave 19 extends global Eulerian evidence to exactly three separated tracked bubbles and two simultaneous pre-contact gaps sharing one authoritative pressure/velocity solve with field-derived multi-front traction, conservation, refinement and permutation evidence. T1-through-global-CFD, overlapping immersed supports, arbitrary bubble/contact graphs, turbulence/compressibility/thermal/rarefied flow and universal sharp moving-interface multiphase Navier-Stokes remain unsupported.",
            "Extend beyond the accepted separated-support three-bubble/two-gap class only with independent field, conservation, refinement and runtime evidence for each broader flow regime.",
            benchmarks=["B09", "B12"],
            features={
                "ambient_flow_reference_model": "MODELED",
                "transient_b12_release": "RESOLVED",
                "resolved_bulk_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "supported_global_two_bubble_single_gap_multiregion_cfd": "MODELED",
                "bounded_three_bubble_two_gap_global_cfd": "MODELED",
                "global_full_domain_multiregion_cfd": "NOT_IMPLEMENTED",
                "arbitrary_multigap_manybubble_t1_cfd": "NOT_IMPLEMENTED",
                "t1_through_global_cfd": "NOT_IMPLEMENTED",
                "overlapping_immersed_supports": "NOT_IMPLEMENTED",
            },
        ),
        "R13": row(
            "SATISFIED",
            [
                "bubblelab/solvers/thinfilm/gas.py",
                "bubblelab/runtime/thinfilm_runtime.py",
                "bubblelab/runtime/contact_thinfilm_event_runtime.py",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-contact-thinfilm-event-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-manybubble-gas-diffusion-network.json",
            ],
            "No baseline R13 gap remains. Pressure-driven transfer is available in the accepted pair/shared-film path and Wave 19 independently qualifies a fixed-topology many-bubble network with at least three gas regions and two simultaneously active real shared-film transfer edges, conservative equal-and-opposite molar flux, coupled amount/pressure/volume evolution, measured coarsening, deterministic replay and user enable/disable control.",
            "Retain exact conservation, stable gas identities, pressure/amount/volume feedback and explicit fixed-topology support. Dynamic shared-film formation, T1/rupture/coalescence/vanishing-region surgery and unrestricted topology-changing gas transport remain separate higher-fidelity extensions rather than baseline R13 blockers.",
            benchmarks=["B15"],
            features={
                "pairwise_gas_diffusion": "MODELED",
                "contact_integrated_gas_transfer": "MODELED",
                "supported_manybubble_pressure_driven_gas_network": "MODELED",
                "network_pressure_amount_volume_feedback": "MODELED",
                "deterministic_conservative_network_runtime": "RESOLVED",
                "gas_transfer_enable_disable": "RESOLVED",
            },
        ),
        "R35": row(
            "PARTIAL",
            [
                "bubblelab/viewer/src/lab.ts",
                "bubblelab/solvers/transient/release_benchmarks.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-noslip-wall-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-precontact-multiregion-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-t1-production-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-global-multiregion-cfd-coupling.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-general-3d-t1-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-singular-breakup-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-manybubble-gas-diffusion-network.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-multigap-manybubble-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-direct-3d-t1-hydrodynamics.json",
            ],
            "Multiple fidelity/backend modes, exact transient gates, fixed-SDF walls, local and bounded global CFD, conservative many-bubble gas diffusion, bounded direct-geometry 3D T1 and supported axisymmetric pinch-off are accepted. Maximum Realism is still not one unrestricted path because topology-changing gas transport, T1-through-global-CFD/overlapping supports, unrestricted continuous/singular 3D T1, deforming-wall CFD and rim/ligament/droplet-spray or arbitrary multi-neck breakup remain unavailable.",
            "Keep every lower-fidelity and supported-class mode explicit and qualify each remaining unrestricted maximum-realism extension independently before presenting it as general.",
            features={
                "multi_backend_fidelity": "MODELED",
                "exact_transient_release_qualification": "RESOLVED",
                "supported_topology_transactions": "RESOLVED",
                "resolved_fixed_sdf_no_slip_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "supported_global_two_bubble_single_gap_multiregion_cfd": "MODELED",
                "bounded_genuine_non_coplanar_3d_t1": "RESOLVED",
                "supported_axisymmetric_slender_neck_pinchoff": "MODELED",
                "supported_manybubble_pressure_driven_gas_network": "MODELED",
                "bounded_three_bubble_two_gap_global_cfd": "MODELED",
                "bounded_direct_geometry_3d_t1_hydrodynamics": "MODELED",
                "maximum_realism_integrated": "NOT_IMPLEMENTED",
            },
        ),
        "R38": row(
            "PARTIAL",
            [
                "bubblelab/runtime/transient_network_runtime.py",
                "bubblelab/runtime/contact_thinfilm_event_runtime.py",
                "bubblelab/runtime/server/live_editing.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/viewer/MOBILE_WEBKIT_VERIFICATION.md",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-live-runtime-editing.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-noslip-wall-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-precontact-multiregion-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-global-multiregion-cfd-coupling.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-general-3d-t1-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-singular-breakup-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-manybubble-gas-diffusion-network.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-multigap-manybubble-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-direct-3d-t1-hydrodynamics.json",
            ],
            "Wave 19 adds conservative many-bubble gas diffusion, a bounded shared-field three-bubble/two-gap global CFD runtime, and bounded direct-geometry 3D T1 hydrodynamics to the already integrated construction, wall, shared-film, event and topology paths. Final integrated acceptance is still directly blocked by missing physical iPhone Safari/device-GPU/native-touch qualification. Unrestricted topology-changing gas diffusion, T1-through-global-CFD/overlapping immersed supports, universal sharp-interface multiphase CFD, unrestricted arbitrary 3D T1/continuum liquid-border hydrodynamics, rim/ligament/droplet-spray, unrestricted 3D multi-neck breakup, deforming-wall CFD and arbitrary coupled live surgery remain explicit higher-fidelity scope limits.",
            "Archive physical iPhone Safari/native-hardware evidence for the direct R38 device requirement and preserve every higher-fidelity scope limit until independently implemented and qualified.",
            benchmarks=["B03", "B07", "B08", "B12", "B14", "B15", "B16"],
            features={
                "multi_bubble_canonical_runtime": "RESOLVED",
                "contact_thinfilm_event_chain": "RESOLVED",
                "browser_live_solver_transport": "RESOLVED",
                "production_fragmentation": "RESOLVED",
                "supported_t1_transaction": "RESOLVED",
                "arbitrary_live_runtime_creation": "RESOLVED",
                "live_runtime_bubble_editing": "RESOLVED",
                "resolved_no_slip_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "supported_global_two_bubble_single_gap_multiregion_cfd": "MODELED",
                "bounded_genuine_non_coplanar_3d_t1": "RESOLVED",
                "supported_axisymmetric_slender_neck_pinchoff": "MODELED",
                "deterministic_pinchoff_fragmentation_restart": "RESOLVED",
                "supported_manybubble_pressure_driven_gas_network": "MODELED",
                "bounded_three_bubble_two_gap_global_cfd": "MODELED",
                "bounded_direct_geometry_3d_t1_hydrodynamics": "MODELED",
                "physical_iphone_safari": "NOT_IMPLEMENTED",
                "native_hardware_multitouch": "NOT_IMPLEMENTED",
                "fully_coupled_precontact_lubrication": "NOT_IMPLEMENTED",
                "global_full_domain_multiregion_cfd": "NOT_IMPLEMENTED",
                "arbitrary_multigap_manybubble_t1_cfd": "NOT_IMPLEMENTED",
                "t1_through_global_cfd": "NOT_IMPLEMENTED",
                "overlapping_immersed_supports": "NOT_IMPLEMENTED",
                "general_3d_t1": "NOT_IMPLEMENTED",
                "unrestricted_topology_changing_gas_diffusion": "NOT_IMPLEMENTED",
                "singular_pinchoff_rim_spray": "NOT_IMPLEMENTED",
                "retracting_rim_ligament_droplet_spray": "NOT_IMPLEMENTED",
                "unrestricted_3d_multineck_pinchoff": "NOT_IMPLEMENTED",
                "arbitrary_deforming_moving_wall_cfd": "NOT_IMPLEMENTED",
                "arbitrary_coupled_topology_live_surgery": "NOT_IMPLEMENTED",
            },
        ),
        "R39": row(
            "PARTIAL",
            [
                "bubblelab/docs/physics/PHYSICS_MODEL.md",
                "bubblelab/runtime/transient_network_runtime.py",
                "bubblelab/runtime/contact_thinfilm_event_runtime.py",
                "bubblelab/runtime/server/live_editing.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-live-runtime-editing.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-noslip-wall-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-precontact-multiregion-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-global-multiregion-cfd-coupling.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-general-3d-t1-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-singular-breakup-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-manybubble-gas-diffusion-network.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-multigap-manybubble-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-direct-3d-t1-hydrodynamics.json",
            ],
            "Bubble Lab now combines authoritative construction/editing, fixed-SDF no-slip wall flow, local and bounded global multi-gap CFD, conservative many-bubble gas diffusion, canonical shared films/events, bounded direct-geometry 3D T1 and supported axisymmetric pinch-off with deterministic fragmentation restart. The ultimate laboratory statement remains incomplete while physical-device qualification and declared unrestricted topology-changing/general/singular maximum-realism classes remain open.",
            "Preserve every supported-class boundary and close the remaining physical-validity/device gaps with measured evidence rather than treating breadth of existing modes as unrestricted maximum-realism completion.",
            features={
                "physical_laboratory_direction": "MODELED",
                "integrated_physics_runtime": "RESOLVED",
                "authoritative_live_construction": "RESOLVED",
                "resolved_fixed_sdf_no_slip_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "supported_global_two_bubble_single_gap_multiregion_cfd": "MODELED",
                "bounded_genuine_non_coplanar_3d_t1": "RESOLVED",
                "supported_axisymmetric_slender_neck_pinchoff": "MODELED",
                "supported_manybubble_pressure_driven_gas_network": "MODELED",
                "bounded_three_bubble_two_gap_global_cfd": "MODELED",
                "bounded_direct_geometry_3d_t1_hydrodynamics": "MODELED",
                "complete_physical_laboratory": "NOT_IMPLEMENTED",
            },
        ),
    }
)
