"""Post-Wave-17 evidence overlay for the Bubble Lab completion catalog."""
from __future__ import annotations

from copy import deepcopy

from .catalog import row
from .wave15_catalog import CATALOG as WAVE15_CATALOG


CATALOG = deepcopy(WAVE15_CATALOG)
CATALOG.update(
    {
        "R1": row(
            "PARTIAL",
            [
                "bubblelab/docs/physics/PHYSICS_MODEL.md",
                "bubblelab/runtime/session_control.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-live-runtime-editing.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-noslip-wall-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-precontact-multiregion-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-global-multiregion-cfd-coupling.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-general-3d-t1-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-singular-breakup-cfd-foundation.json",
            ],
            "Wave 17 adds a supported global-domain two-bubble/single-gap multi-region CFD path, a genuinely non-coplanar bounded 3D T1 transaction, and a dynamically evolved single smooth axisymmetric slender-neck pinch-off path. The ultimate maximum-realism laboratory is still incomplete because arbitrary simultaneous multi-gap/many-bubble/T1 CFD, unrestricted admissible 3D T1, retracting-rim/ligament/droplet-spray and unrestricted multi-neck 3D breakup, plus physical-device qualification remain outside accepted evidence.",
            "Preserve every accepted supported class and close the remaining universal/general/device gaps independently with measured evidence rather than widening claim boundaries by prose.",
            features={
                "physical_solver_stack": "MODELED",
                "exact_transient_release_qualification": "RESOLVED",
                "integrated_topology_slices": "RESOLVED",
                "live_authoritative_transport": "RESOLVED",
                "authoritative_base_transient_live_editing": "RESOLVED",
                "resolved_fixed_sdf_no_slip_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "supported_global_two_bubble_single_gap_multiregion_cfd": "MODELED",
                "bounded_genuine_non_coplanar_3d_t1": "RESOLVED",
                "supported_axisymmetric_slender_neck_pinchoff": "MODELED",
                "maximum_realism_full_coupling": "NOT_IMPLEMENTED",
            },
        ),
        "R9": row(
            "SATISFIED",
            [
                "bubblelab/solvers/equilibrium/plateau.py",
                "bubblelab/runtime/transient_network_runtime.py",
                "bubblelab/scenarios/runtime/transient-network-plateau.scenario.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-transient-network-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-t1-production-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-general-3d-t1-foundation.json",
            ],
            "No baseline R9 gap remains: the accepted equilibrium/transient network provides Plateau force/angle diagnostics and explicit junction geometry, while Wave 17 independently qualifies a genuinely non-coplanar bounded 3D neighbor switch with real adjacency/incidence change, stable gas identities, conservation, deterministic replay, refinement and continuation.",
            "Retain approximately-120-degree diagnostics and explicit topology/incidence records; arbitrary admissible 3D T1 hydrodynamics remain a separate higher-fidelity extension rather than a baseline R9 blocker.",
            benchmarks=["B06"],
            features={
                "plateau_equilibrium": "RESOLVED",
                "dynamic_multi_junction_runtime": "RESOLVED",
                "supported_t1_transaction": "RESOLVED",
                "bounded_genuine_non_coplanar_3d_t1": "RESOLVED",
            },
        ),
        "R10": row(
            "PARTIAL",
            [
                "bubblelab/solvers/transient/solver.py",
                "bubblelab/runtime/transient_network_runtime.py",
                "bubblelab/runtime/contact_runtime.py",
                "bubblelab/runtime/boundary_runtime.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-noslip-wall-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-precontact-multiregion-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-global-multiregion-cfd-coupling.json",
            ],
            "Accepted runtime slices cover free deformation, gravity/wind forcing, contact deformation, resolved fixed-SDF no-slip walls, local thin-gap traction, and Wave-17 global two-bubble/single-gap field-derived pre-contact resistance. A single general maximum-realism runtime still does not combine every requested forcing with arbitrary simultaneous multi-contact, many-gap CFD and deforming-wall classes.",
            "Qualify only the remaining general forcing/contact/wall combinations needed for the maximum-realism claim while retaining the fixed-SDF and single-gap support boundaries.",
            features={
                "transient_free_deformation": "MODELED",
                "network_forcing": "MODELED",
                "contact_deformation": "MODELED",
                "resolved_fixed_sdf_no_slip_wall_cfd": "RESOLVED",
                "local_precontact_thin_gap_traction": "MODELED",
                "supported_global_two_bubble_single_gap_multiregion_cfd": "MODELED",
                "unified_maximum_realism_forcing": "NOT_IMPLEMENTED",
            },
        ),
        "R11": row(
            "PARTIAL",
            [
                "bubblelab/solvers/transient/grid.py",
                "bubblelab/solvers/transient/solver.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-noslip-wall-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-precontact-multiregion-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-global-multiregion-cfd-coupling.json",
            ],
            "Gravity, ambient density/viscosity and wind retain exact release qualification; fixed-SDF no-slip wall flow and the local thin-gap solver remain accepted. Wave 17 additionally qualifies a spatial global-domain 3D pressure/velocity solve for the supported two-bubble/single-gap class with closed-control-volume traction, measured mass/momentum balance, field feedback and asymptotic 10^3/12^3/14^3 refinement. Arbitrary simultaneous multi-gap/many-bubble/T1 CFD, turbulence/compressibility/thermal/rarefied flow and universal full-domain multiphase Navier-Stokes remain unsupported.",
            "Extend beyond the accepted supported global single-gap class only with independent field, conservation, refinement and runtime evidence for each broader flow regime.",
            benchmarks=["B09", "B12"],
            features={
                "ambient_flow_reference_model": "MODELED",
                "transient_b12_release": "RESOLVED",
                "resolved_bulk_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "supported_global_two_bubble_single_gap_multiregion_cfd": "MODELED",
                "global_full_domain_multiregion_cfd": "NOT_IMPLEMENTED",
                "arbitrary_multigap_manybubble_t1_cfd": "NOT_IMPLEMENTED",
            },
        ),
        "R16": row(
            "SATISFIED",
            [
                "bubblelab/solvers/events/engine.py",
                "bubblelab/runtime/event_runtime.py",
                "bubblelab/runtime/fragmentation_runtime.py",
                "bubblelab/runtime/postfragmentation_relaxation.py",
                "bubblelab/solvers/events/pinchoff/solver.py",
                "bubblelab/runtime/tools/run_pinchoff_transition.py",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-fragmentation-production.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-postfragmentation-relaxation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-singular-breakup-cfd-foundation.json",
            ],
            "No baseline R16 gap remains: user/criterion rupture and supported production splitting are accepted, and Wave 17 adds a conservative dynamically evolved single smooth axisymmetric slender-neck hydrodynamic path with inferred pinch time, exact evolved-parent handoff to fragmentation and deterministic post-fragmentation restart.",
            "Retain the supported single-neck axisymmetric scope and deterministic topology handoff. Retracting rims, ligaments, droplets/spray, arbitrary multi-neck breakup and unrestricted fully resolved 3D singular breakup remain later maximum-realism extensions and must not be inferred from this R16 baseline closure.",
            benchmarks=["B16"],
            features={
                "rupture_event": "MODELED",
                "user_burst": "MODELED",
                "production_fragmentation": "RESOLVED",
                "post_fragmentation_relaxation": "MODELED",
                "supported_axisymmetric_slender_neck_pinchoff": "MODELED",
                "deterministic_pinchoff_fragmentation_restart": "RESOLVED",
            },
        ),
        "R35": row(
            "PARTIAL",
            [
                "bubblelab/viewer/src/lab.ts",
                "bubblelab/solvers/transient/release_benchmarks.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-noslip-wall-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-precontact-multiregion-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-t1-production-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-global-multiregion-cfd-coupling.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-general-3d-t1-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-singular-breakup-cfd-foundation.json",
            ],
            "Multiple fidelity/backend modes, exact transient gates, supported topology transactions, fixed-SDF no-slip walls, local thin-gap CFD, supported global two-bubble/single-gap CFD, bounded genuinely non-coplanar 3D T1 and supported axisymmetric pinch-off are accepted. Maximum Realism is still not a single unrestricted path because arbitrary many-gap/many-bubble/T1 CFD, unrestricted admissible 3D T1, rim/ligament/droplet-spray and unrestricted multi-neck 3D breakup remain unavailable.",
            "Keep lower-fidelity and supported-class modes explicit and qualify each remaining unrestricted maximum-realism extension independently before presenting it as general.",
            features={
                "multi_backend_fidelity": "MODELED",
                "exact_transient_release_qualification": "RESOLVED",
                "supported_topology_transactions": "RESOLVED",
                "resolved_fixed_sdf_no_slip_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "supported_global_two_bubble_single_gap_multiregion_cfd": "MODELED",
                "bounded_genuine_non_coplanar_3d_t1": "RESOLVED",
                "supported_axisymmetric_slender_neck_pinchoff": "MODELED",
                "maximum_realism_integrated": "NOT_IMPLEMENTED",
            },
        ),
        "R38": row(
            "PARTIAL",
            [
                "bubblelab/runtime/transient_network_runtime.py",
                "bubblelab/runtime/contact_thinfilm_event_runtime.py",
                "bubblelab/runtime/server/live_editing.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/viewer/MOBILE_WEBKIT_VERIFICATION.md",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-live-runtime-editing.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-noslip-wall-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-precontact-multiregion-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-global-multiregion-cfd-coupling.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-general-3d-t1-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-singular-breakup-cfd-foundation.json",
            ],
            "Wave 17 adds supported global two-bubble/single-gap CFD, bounded genuinely non-coplanar 3D T1 and a supported axisymmetric slender-neck pinch-off/fragmentation restart to the already integrated construction, wall, shared-film, event and topology paths. Final integrated acceptance is still blocked directly by missing physical iPhone Safari/device-GPU/native-touch qualification. Broader arbitrary multi-gap/many-bubble/T1 CFD, unrestricted 3D T1, rim/ligament/droplet-spray, unrestricted 3D multi-neck breakup, deforming-wall CFD and arbitrary live topology surgery remain explicit higher-fidelity scope limits.",
            "Archive physical iPhone Safari/native-hardware evidence for the direct R38 device requirement and preserve every higher-fidelity scope limit until independently implemented and qualified.",
            benchmarks=["B03", "B07", "B08", "B12", "B14", "B15", "B16"],
            features={
                "multi_bubble_canonical_runtime": "RESOLVED",
                "contact_thinfilm_event_chain": "RESOLVED",
                "browser_live_solver_transport": "RESOLVED",
                "production_fragmentation": "RESOLVED",
                "supported_t1_transaction": "RESOLVED",
                "arbitrary_live_runtime_creation": "RESOLVED",
                "live_runtime_bubble_editing": "RESOLVED",
                "resolved_no_slip_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "supported_global_two_bubble_single_gap_multiregion_cfd": "MODELED",
                "bounded_genuine_non_coplanar_3d_t1": "RESOLVED",
                "supported_axisymmetric_slender_neck_pinchoff": "MODELED",
                "deterministic_pinchoff_fragmentation_restart": "RESOLVED",
                "physical_iphone_safari": "NOT_IMPLEMENTED",
                "native_hardware_multitouch": "NOT_IMPLEMENTED",
                "fully_coupled_precontact_lubrication": "NOT_IMPLEMENTED",
                "global_full_domain_multiregion_cfd": "NOT_IMPLEMENTED",
                "arbitrary_multigap_manybubble_t1_cfd": "NOT_IMPLEMENTED",
                "general_3d_t1": "NOT_IMPLEMENTED",
                "singular_pinchoff_rim_spray": "NOT_IMPLEMENTED",
                "retracting_rim_ligament_droplet_spray": "NOT_IMPLEMENTED",
                "unrestricted_3d_multineck_pinchoff": "NOT_IMPLEMENTED",
                "arbitrary_deforming_moving_wall_cfd": "NOT_IMPLEMENTED",
                "arbitrary_coupled_topology_live_surgery": "NOT_IMPLEMENTED",
            },
        ),
        "R39": row(
            "PARTIAL",
            [
                "bubblelab/docs/physics/PHYSICS_MODEL.md",
                "bubblelab/runtime/transient_network_runtime.py",
                "bubblelab/runtime/contact_thinfilm_event_runtime.py",
                "bubblelab/runtime/server/live_editing.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-live-runtime-editing.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-noslip-wall-runtime-integration.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-precontact-multiregion-cfd-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-global-multiregion-cfd-coupling.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-general-3d-t1-foundation.json",
                "bubblelab/validation/completion/evidence/historical-deliveries/bubble-singular-breakup-cfd-foundation.json",
            ],
            "Bubble Lab now combines authoritative construction/editing, fixed-SDF no-slip wall flow, local thin-gap and supported global two-bubble CFD, canonical shared films/events, bounded genuine 3D T1 and supported axisymmetric pinch-off with deterministic fragmentation restart. The ultimate laboratory statement remains incomplete while physical-device qualification and declared unrestricted many-bubble/multi-gap/3D singular maximum-realism classes remain open.",
            "Preserve supported-class boundaries and close the remaining physical-validity/device gaps with measured evidence rather than treating breadth of existing modes as unrestricted maximum-realism completion.",
            features={
                "physical_laboratory_direction": "MODELED",
                "integrated_physics_runtime": "RESOLVED",
                "authoritative_live_construction": "RESOLVED",
                "resolved_fixed_sdf_no_slip_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "supported_global_two_bubble_single_gap_multiregion_cfd": "MODELED",
                "bounded_genuine_non_coplanar_3d_t1": "RESOLVED",
                "supported_axisymmetric_slender_neck_pinchoff": "MODELED",
                "complete_physical_laboratory": "NOT_IMPLEMENTED",
            },
        ),
    }
)
