"""Post-Wave-15 evidence overlay for the Bubble Lab completion catalog."""
from __future__ import annotations

from copy import deepcopy

from .catalog import row
from .wave13_catalog import CATALOG as WAVE13_CATALOG


CATALOG = deepcopy(WAVE13_CATALOG)
CATALOG.update(
    {
        "R1": row(
            "PARTIAL",
            [
                "bubblelab/docs/physics/PHYSICS_MODEL.md",
                "bubblelab/runtime/session_control.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "tasks/bubble-live-runtime-editing/deliverable.json",
                "tasks/bubble-noslip-wall-runtime-integration/deliverable.json",
                "tasks/bubble-precontact-multiregion-cfd-foundation/deliverable.json",
            ],
            "Wave 15 closes the authoritative base-transient live-edit gap, integrates resolved fixed-SDF no-slip wall flow, and adds numerical local thin-gap pressure/velocity traction feedback for the supported isolated two-front class. The ultimate maximum-realism laboratory is still incomplete because global full-domain multi-region coupling, general 3D topology/singular breakup physics, and physical-device qualification remain outside accepted evidence.",
            "Preserve the new Wave-15 capabilities as scoped evidence and close the remaining maximum-realism/device gaps independently rather than broadening the supported classes by prose.",
            features={
                "physical_solver_stack": "MODELED",
                "exact_transient_release_qualification": "RESOLVED",
                "integrated_topology_slices": "RESOLVED",
                "live_authoritative_transport": "RESOLVED",
                "authoritative_base_transient_live_editing": "RESOLVED",
                "resolved_fixed_sdf_no_slip_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "maximum_realism_full_coupling": "NOT_IMPLEMENTED",
            },
        ),
        "R4": row(
            "SATISFIED",
            [
                "bubblelab/contracts/scenario.schema.json",
                "bubblelab/viewer/src/lab.ts",
                "bubblelab/viewer/src/liveSessionPanel.ts",
                "bubblelab/runtime/session_control.py",
                "bubblelab/runtime/server/live_editing.py",
                "tasks/bubble-live-runtime-editing/deliverable.json",
            ],
            "No baseline R4 gap remains for authoritative bubble creation: a paused authoritative session can add a bubble at the current simulation time with X/Y/Z position, radius, X/Y/Z velocity and surface tension, then continue the same solver session with deterministic provenance.",
            "Retain atomic validation, stable identifiers, same-session continuation and editor placement coverage when extending optional creation parameters.",
            features={
                "scenario_bubble_creation": "RESOLVED",
                "arbitrary_live_runtime_creation": "RESOLVED",
                "live_add_position_radius_velocity": "RESOLVED",
                "same_session_continuation": "RESOLVED",
            },
        ),
        "R10": row(
            "PARTIAL",
            [
                "bubblelab/solvers/transient/solver.py",
                "bubblelab/runtime/transient_network_runtime.py",
                "bubblelab/runtime/contact_runtime.py",
                "bubblelab/runtime/boundary_runtime.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "tasks/bubble-noslip-wall-runtime-integration/deliverable.json",
                "tasks/bubble-precontact-multiregion-cfd-foundation/deliverable.json",
            ],
            "Accepted runtime slices now include physical free deformation, wind/gravity forcing, contact deformation, resolved fixed-SDF no-slip wall response and numerical local pre-contact thin-gap traction. A single general maximum-realism runtime still does not combine every requested forcing, simultaneous contact and arbitrary moving/deforming-wall class.",
            "Qualify only the remaining forcing/contact/wall combinations needed for the maximum-realism claim while retaining the fixed-SDF and isolated-gap support boundaries.",
            features={
                "transient_free_deformation": "MODELED",
                "network_forcing": "MODELED",
                "contact_deformation": "MODELED",
                "resolved_fixed_sdf_no_slip_wall_cfd": "RESOLVED",
                "local_precontact_thin_gap_traction": "MODELED",
                "unified_maximum_realism_forcing": "NOT_IMPLEMENTED",
            },
        ),
        "R11": row(
            "PARTIAL",
            [
                "bubblelab/solvers/transient/grid.py",
                "bubblelab/solvers/transient/solver.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "tasks/bubble-noslip-wall-runtime-integration/deliverable.json",
                "tasks/bubble-precontact-multiregion-cfd-foundation/deliverable.json",
            ],
            "Gravity, ambient density/viscosity and wind remain modeled with exact B12 release qualification; Wave 15 additionally resolves canonical fixed-SDF no-slip wall coupling and a numerical isolated thin-gap pressure/velocity field with traction feedback. Global full-domain multi-region Navier-Stokes coupling, simultaneous multi-gap CFD and broader turbulence/high-end combinations remain unimplemented.",
            "Extend Eulerian/multi-region coupling beyond the accepted fixed-wall and isolated local-gap classes only with independent field, conservation, refinement and runtime evidence.",
            benchmarks=["B09", "B12"],
            features={
                "ambient_flow_reference_model": "MODELED",
                "transient_b12_release": "RESOLVED",
                "resolved_bulk_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "global_full_domain_multiregion_cfd": "NOT_IMPLEMENTED",
            },
        ),
        "R17": row(
            "SATISFIED",
            [
                "bubblelab/solvers/boundary/contact.py",
                "bubblelab/runtime/boundary_runtime.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/viewer/src/lab.ts",
                "tasks/bubble-boundary-ui-integration/deliverable.json",
                "tasks/bubble-noslip-wall-runtime-integration/deliverable.json",
            ],
            "No baseline R17 gap remains for the accepted boundary classes: tracked-front wall contact and wettability controls coexist with canonical resolved bulk no-slip flow against configured fixed SDF solids, including stationary and spatially uniform moving-wall velocity.",
            "Retain measured Eulerian wall diagnostics and explicit fixed-geometry/uniform-velocity scope; arbitrary deforming wall geometry is a separate higher-fidelity extension rather than evidence against the accepted R17 baseline.",
            features={
                "tracked_front_boundary_contact": "MODELED",
                "solid_boundary_ui_integration": "RESOLVED",
                "fixed_sdf_solid_obstacles": "RESOLVED",
                "resolved_no_slip_wall_cfd": "RESOLVED",
            },
        ),
        "R27": row(
            "SATISFIED",
            [
                "bubblelab/viewer/src/lab.ts",
                "bubblelab/viewer/src/liveSessionPanel.ts",
                "bubblelab/runtime/session_control.py",
                "bubblelab/runtime/server/live_editing.py",
                "tasks/bubble-live-runtime-editing/deliverable.json",
            ],
            "No baseline R27 direct-manipulation gap remains: selection/inspection and scenario burst controls are retained, while a PAUSED authoritative session now supports add, delete, move, resize and velocity edits, with editing explicitly separated from RUNNING execution and followed by same-session physical continuation.",
            "Keep live edits atomic and PAUSED-only, preserve deterministic provenance, and do not reinterpret this baseline as arbitrary surgery through pre-existing shared-film/network/T1/thin-film/event states.",
            features={
                "scenario_direct_manipulation": "RESOLVED",
                "live_session_control": "RESOLVED",
                "live_runtime_bubble_editing": "RESOLVED",
                "paused_edit_run_separation": "RESOLVED",
            },
        ),
        "R35": row(
            "PARTIAL",
            [
                "bubblelab/viewer/src/lab.ts",
                "bubblelab/solvers/transient/release_benchmarks.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "tasks/bubble-noslip-wall-runtime-integration/deliverable.json",
                "tasks/bubble-precontact-multiregion-cfd-foundation/deliverable.json",
                "tasks/bubble-t1-production-foundation/deliverable.json",
            ],
            "Multiple fidelity/backend modes, exact transient release gates, supported topology transactions, resolved fixed-SDF no-slip walls and a resolved local thin-gap CFD foundation are accepted. Maximum Realism is still not a single general path: the thin-gap solver is isolated/axisymmetric, T1 is supported-class only, and singular breakup/rim/spray and global full-domain multi-region coupling remain unavailable.",
            "Keep lower-fidelity and supported-class modes explicit and qualify each remaining maximum-realism extension independently before presenting it as general.",
            features={
                "multi_backend_fidelity": "MODELED",
                "exact_transient_release_qualification": "RESOLVED",
                "supported_topology_transactions": "RESOLVED",
                "resolved_fixed_sdf_no_slip_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "maximum_realism_integrated": "NOT_IMPLEMENTED",
            },
        ),
        "R38": row(
            "PARTIAL",
            [
                "bubblelab/runtime/transient_network_runtime.py",
                "bubblelab/runtime/contact_thinfilm_event_runtime.py",
                "bubblelab/runtime/server/live_editing.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "bubblelab/viewer/MOBILE_WEBKIT_VERIFICATION.md",
                "tasks/bubble-live-runtime-editing/deliverable.json",
                "tasks/bubble-noslip-wall-runtime-integration/deliverable.json",
                "tasks/bubble-precontact-multiregion-cfd-foundation/deliverable.json",
            ],
            "Wave 15 closes the prior integrated arbitrary live-edit and resolved fixed-SDF wall-CFD gaps and adds supported-class numerical pre-contact thin-gap fields/traction. Final integrated acceptance is still blocked by missing physical iPhone Safari/device-GPU/native-touch qualification, while general 3D T1, singular breakup/rim/spray, global full-domain multi-region CFD and arbitrary live topology surgery remain explicitly outside their supported classes.",
            "Archive physical iPhone Safari/native-hardware evidence for the direct R38 device requirement, and keep the remaining higher-fidelity scope limits explicit until independently implemented and qualified.",
            benchmarks=["B03", "B07", "B08", "B12", "B14", "B15", "B16"],
            features={
                "multi_bubble_canonical_runtime": "RESOLVED",
                "contact_thinfilm_event_chain": "RESOLVED",
                "browser_live_solver_transport": "RESOLVED",
                "production_fragmentation": "RESOLVED",
                "supported_t1_transaction": "RESOLVED",
                "arbitrary_live_runtime_creation": "RESOLVED",
                "live_runtime_bubble_editing": "RESOLVED",
                "resolved_no_slip_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "physical_iphone_safari": "NOT_IMPLEMENTED",
                "native_hardware_multitouch": "NOT_IMPLEMENTED",
                "fully_coupled_precontact_lubrication": "NOT_IMPLEMENTED",
                "global_full_domain_multiregion_cfd": "NOT_IMPLEMENTED",
                "general_3d_t1": "NOT_IMPLEMENTED",
                "singular_pinchoff_rim_spray": "NOT_IMPLEMENTED",
                "arbitrary_coupled_topology_live_surgery": "NOT_IMPLEMENTED",
            },
        ),
        "R39": row(
            "PARTIAL",
            [
                "bubblelab/docs/physics/PHYSICS_MODEL.md",
                "bubblelab/runtime/transient_network_runtime.py",
                "bubblelab/runtime/contact_thinfilm_event_runtime.py",
                "bubblelab/runtime/server/live_editing.py",
                "bubblelab/runtime/runner.py",
                "bubblelab/runtime/precontact_cfd_runtime.py",
                "tasks/bubble-live-runtime-editing/deliverable.json",
                "tasks/bubble-noslip-wall-runtime-integration/deliverable.json",
                "tasks/bubble-precontact-multiregion-cfd-foundation/deliverable.json",
            ],
            "Bubble Lab now supports authoritative construction/editing of the base transient system, resolved fixed-SDF no-slip wall flow, numerical local pre-contact thin-gap fields/traction, canonical shared films/events and supported topology transactions. The ultimate laboratory statement remains incomplete while physical-device qualification and declared global/general/singular maximum-realism physics classes remain open.",
            "Preserve supported-class boundaries and close the remaining physical validity/device gaps with measured evidence rather than treating breadth of existing modes as general maximum-realism completion.",
            features={
                "physical_laboratory_direction": "MODELED",
                "integrated_physics_runtime": "RESOLVED",
                "authoritative_live_construction": "RESOLVED",
                "resolved_fixed_sdf_no_slip_wall_cfd": "RESOLVED",
                "local_resolved_precontact_thin_gap_cfd": "MODELED",
                "complete_physical_laboratory": "NOT_IMPLEMENTED",
            },
        ),
    }
)
